// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storge.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ZTMAttachment;
@class ZTMBlacklist;
@class ZTMChannelLocalProfile;
@class ZTMConversationDraft;
@class ZTMConversationLocalProfile;
@class ZTMSense;
@class ZTMSenseDraft;
@class ZTMTalkMessage;
@class ZTMUserDescription;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ZTMStorgeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ZTMStorgeRoot : GPBRootObject
@end

#pragma mark - ZTMAttachment

typedef GPB_ENUM(ZTMAttachment_FieldNumber) {
  ZTMAttachment_FieldNumber_Path = 1,
  ZTMAttachment_FieldNumber_Size = 2,
  ZTMAttachment_FieldNumber_Id_p = 3,
  ZTMAttachment_FieldNumber_UploadedSize = 4,
  ZTMAttachment_FieldNumber_IsUploaded = 5,
};

@interface ZTMAttachment : GPBMessage

/** 文件完整路径 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

/** 文件大小(byte) */
@property(nonatomic, readwrite) int64_t size;

/** 附件的id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 已经上传的大小 */
@property(nonatomic, readwrite) int64_t uploadedSize;

/** 是否已经上传完成 */
@property(nonatomic, readwrite) int32_t isUploaded;

@end

#pragma mark - ZTMLocalProfile

typedef GPB_ENUM(ZTMLocalProfile_FieldNumber) {
  ZTMLocalProfile_FieldNumber_UserId = 1,
  ZTMLocalProfile_FieldNumber_Version = 2,
  ZTMLocalProfile_FieldNumber_Users = 3,
};

@interface ZTMLocalProfile : GPBMessage

/** 当前用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 当前程序版本 */
@property(nonatomic, readwrite) int32_t version;

/** 历史登录过的用户 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, ZTMUserDescription*> *users;
/** The number of items in @c users without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger users_Count;

@end

#pragma mark - ZTMUserLocalProfile

typedef GPB_ENUM(ZTMUserLocalProfile_FieldNumber) {
  ZTMUserLocalProfile_FieldNumber_TokenServer = 1,
  ZTMUserLocalProfile_FieldNumber_ChannelProfiles = 2,
  ZTMUserLocalProfile_FieldNumber_Blacklist = 3,
  ZTMUserLocalProfile_FieldNumber_ConversationProfiles = 4,
  ZTMUserLocalProfile_FieldNumber_User = 5,
  ZTMUserLocalProfile_FieldNumber_RecommendAttitude = 6,
};

@interface ZTMUserLocalProfile : GPBMessage

/** 用户Token Server Key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tokenServer;

/** 频道相关的配置 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, ZTMChannelLocalProfile*> *channelProfiles;
/** The number of items in @c channelProfiles without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger channelProfiles_Count;

/** 黑名单 */
@property(nonatomic, readwrite, strong, null_resettable) ZTMBlacklist *blacklist;
/** Test to see if @c blacklist has been set. */
@property(nonatomic, readwrite) BOOL hasBlacklist;

/** 聊天会话相关配置 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, ZTMConversationLocalProfile*> *conversationProfiles;
/** The number of items in @c conversationProfiles without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger conversationProfiles_Count;

/** 完整的用户对象 */
@property(nonatomic, readwrite, strong, null_resettable) ZTMUserDescription *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

/** 推荐表态参与的日期字符串 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *recommendAttitude;

@end

#pragma mark - ZTMChannelLocalProfile

typedef GPB_ENUM(ZTMChannelLocalProfile_FieldNumber) {
  ZTMChannelLocalProfile_FieldNumber_IndictedSensesArray = 2,
  ZTMChannelLocalProfile_FieldNumber_Drafts = 3,
};

@interface ZTMChannelLocalProfile : GPBMessage

/** 举报的感言 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *indictedSensesArray;
/** The number of items in @c indictedSensesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger indictedSensesArray_Count;

/** 草稿 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, ZTMSenseDraft*> *drafts;
/** The number of items in @c drafts without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger drafts_Count;

@end

#pragma mark - ZTMSenseDraft

typedef GPB_ENUM(ZTMSenseDraft_FieldNumber) {
  ZTMSenseDraft_FieldNumber_Sense = 3,
  ZTMSenseDraft_FieldNumber_AttachmentsArray = 5,
};

@interface ZTMSenseDraft : GPBMessage

/** 结构化数据 */
@property(nonatomic, readwrite, strong, null_resettable) ZTMSense *sense;
/** Test to see if @c sense has been set. */
@property(nonatomic, readwrite) BOOL hasSense;

/** 多个附件 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ZTMAttachment*> *attachmentsArray;
/** The number of items in @c attachmentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attachmentsArray_Count;

@end

#pragma mark - ZTMConversationLocalProfile

typedef GPB_ENUM(ZTMConversationLocalProfile_FieldNumber) {
  ZTMConversationLocalProfile_FieldNumber_Drafts = 1,
  ZTMConversationLocalProfile_FieldNumber_Unread = 2,
  ZTMConversationLocalProfile_FieldNumber_ReadedSpeach = 3,
};

@interface ZTMConversationLocalProfile : GPBMessage

/** 草稿 */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32ObjectDictionary<ZTMConversationDraft*> *drafts;
/** The number of items in @c drafts without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger drafts_Count;

/** 未读消息数 */
@property(nonatomic, readwrite) int32_t unread;

/** 按时间存最近的20个 */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringUInt32Dictionary *readedSpeach;
/** The number of items in @c readedSpeach without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger readedSpeach_Count;

@end

#pragma mark - ZTMConversationDraft

typedef GPB_ENUM(ZTMConversationDraft_FieldNumber) {
  ZTMConversationDraft_FieldNumber_CreateAt = 1,
  ZTMConversationDraft_FieldNumber_IsSended = 2,
  ZTMConversationDraft_FieldNumber_Message = 3,
  ZTMConversationDraft_FieldNumber_Attachment = 4,
};

@interface ZTMConversationDraft : GPBMessage

/** 草稿的创建时间，作为ID来使用 */
@property(nonatomic, readwrite) uint32_t createAt;

/** 发送的状态 */
@property(nonatomic, readwrite) int32_t isSended;

/** 结构化数据 */
@property(nonatomic, readwrite, strong, null_resettable) ZTMTalkMessage *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

/** 附件 */
@property(nonatomic, readwrite, strong, null_resettable) ZTMAttachment *attachment;
/** Test to see if @c attachment has been set. */
@property(nonatomic, readwrite) BOOL hasAttachment;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
